services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ../api
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: ../web
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  db-data:
